#!/bin/bash
# 尺度转换修正验证测试脚本

echo "========================================"
echo "尺度转换修正验证测试"
echo "========================================"
echo ""

echo "测试1: 简化耦合模式 (testexample_simple_coupling.jl)"
echo "----------------------------------------"
echo "预期结果:"
echo "  - 总功率: ~0.5-0.8 W"
echo "  - 温升: ~10-20 K"
echo "  - 最终温度: ~308-318 K"
echo ""
echo "运行中..."
julia example/testexample_simple_coupling.jl 2>&1 | tee output/simple_coupling_test.log
echo ""
echo "结果已保存到: output/simple_coupling_test.log"
echo ""

echo "========================================"
echo "测试2: 多SPMe并行模式 (testexample.jl)"
echo "----------------------------------------"
echo "预期结果:"
echo "  - 总功率: ~0.5-0.8 W"
echo "  - 温升: ~10-20 K (如果运行3600秒)"
echo "  - 电压降: ~0.67 V"
echo ""
echo "运行中..."
julia example/testexample.jl 2>&1 | tee output/multi_spme_test.log
echo ""
echo "结果已保存到: output/multi_spme_test.log"
echo ""

echo "========================================"
echo "测试3: 集总热模型 (thermal_example.jl)"
echo "----------------------------------------"
echo "预期结果:"
echo "  - 内热源: ~0.7-0.8 W"
echo "  - 温升: ~10-15 K"
echo ""
echo "运行中..."
julia example/thermal_example.jl 2>&1 | tee output/lumped_test.log
echo ""
echo "结果已保存到: output/lumped_test.log"
echo ""

echo "========================================"
echo "测试完成"
echo "========================================"
echo ""
echo "检查要点:"
echo "1. 三个模型的总功率应该接近 (~0.5-0.8 W)"
echo "2. 温升应该合理 (~10-20 K)"
echo "3. 简化耦合和多SPMe的温升应该相近"
echo ""
echo "详细分析请查看:"
echo "  - /workspace/docs/最终修正_尺度转换方向.md"
echo "  - /workspace/docs/尺度转换正确逻辑.md"
